apiVersion: apps/v1
kind: Deployment
metadata:
    name: docker-k8s-deployment
    labels:
        app: docker-k8s
spec: 
    replicas: 1
    selector:
        matchLabels:
            app: docker-k8s
    template:
        metadata:
            labels:
                app: docker-k8s
        spec:
            containers:
            - name: docker-k8s
              image: anuththarajayakody/it19114040-assignment:0a37bacf97ee4a8b2b69ae86e9ac33c545288029
              ports:
              - containerPort: 8086
      